version: "3.6"
services:
  server:
    image: eviedigital:ppp-week1.2
    ports:
      - "8080:8080"
    command:
      - nix-shell
      - --run
      - "cd plutus-playground-client && plutus-playground-server"
  client:
    image: eviedigital:ppp-week1.2
    command:
      - nix-shell
      - --run
      - "cd plutus-playground-client && npm run start"
    depends_on:
      - server
    ports:
      - "8009:8009"
    links:
      - server
